spring.application.name=MySpringBoot3Project
# port ?? ??
#server.port=8087

# ????? ???? ??
myboot.age=${random.int(1,100)}
myboot.fullName=${myboot.name} Boot

# ?? ???? profile ???? - prod|test
spring.profiles.active=prod

# log file? ??? ????? ??
logging.file.path=logs

management.endpoints.web.exposure.include=*

spring.boot.admin.client.url=http://localhost:8090